// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/threatcl/spec"
)

type Attributes struct {
	NewInitiative  *bool   `json:"newInitiative,omitempty"`
	InternetFacing *bool   `json:"internetFacing,omitempty"`
	InitiativeSize *string `json:"initiativeSize,omitempty"`
}

type DataStore struct {
	Name             string  `json:"name"`
	TrustZone        *string `json:"trustZone,omitempty"`
	InformationAsset *string `json:"informationAsset,omitempty"`
}

type ExternalElement struct {
	Name      string  `json:"name"`
	TrustZone *string `json:"trustZone,omitempty"`
}

type Flow struct {
	Name string `json:"name"`
	From string `json:"from"`
	To   string `json:"to"`
}

type Process struct {
	Name      string  `json:"name"`
	TrustZone *string `json:"trustZone,omitempty"`
}

type Query struct {
}

type RiskRating struct {
	Likelihood            string  `json:"likelihood"`
	Impact                string  `json:"impact"`
	Severity              string  `json:"severity"`
	Rationale             *string `json:"rationale,omitempty"`
	InherentScore         float64 `json:"inherentScore"`
	ResidualScore         float64 `json:"residualScore"`
	ResidualSeverity      string  `json:"residualSeverity"`
	ResidualRiskReduction float64 `json:"residualRiskReduction"`
}

type SeverityCount struct {
	Severity string `json:"severity"`
	Count    int    `json:"count"`
}

type Statistics struct {
	TotalThreatModels      int              `json:"totalThreatModels"`
	TotalThreats           int              `json:"totalThreats"`
	TotalInformationAssets int              `json:"totalInformationAssets"`
	TotalControls          int              `json:"totalControls"`
	ImplementedControls    int              `json:"implementedControls"`
	AverageRiskReduction   *float64         `json:"averageRiskReduction,omitempty"`
	ThreatsWithRisk        int              `json:"threatsWithRisk"`
	SeverityCounts         []*SeverityCount `json:"severityCounts"`
}

type ThreatFilter struct {
	Name                   *string  `json:"name,omitempty"`
	Impacts                []string `json:"impacts,omitempty"`
	Stride                 []string `json:"stride,omitempty"`
	HasImplementedControls *bool    `json:"hasImplementedControls,omitempty"`
	Severity               []string `json:"severity,omitempty"`
}

type ThreatModel struct {
	Name                   string                       `json:"name"`
	Author                 string                       `json:"author"`
	Description            *string                      `json:"description,omitempty"`
	Link                   *string                      `json:"link,omitempty"`
	DiagramLink            *string                      `json:"diagramLink,omitempty"`
	Repository             []string                     `json:"repository,omitempty"`
	CreatedAt              *int                         `json:"createdAt,omitempty"`
	UpdatedAt              *int                         `json:"updatedAt,omitempty"`
	Attributes             *Attributes                  `json:"attributes,omitempty"`
	AdditionalAttributes   []*spec.AdditionalAttribute  `json:"additionalAttributes,omitempty"`
	InformationAssets      []*spec.InformationAsset     `json:"informationAssets"`
	Threats                []*spec.Threat               `json:"threats"`
	UseCases               []*spec.UseCase              `json:"useCases"`
	Exclusions             []*spec.Exclusion            `json:"exclusions"`
	ThirdPartyDependencies []*spec.ThirdPartyDependency `json:"thirdPartyDependencies"`
	DataFlowDiagrams       []*spec.DataFlowDiagram      `json:"dataFlowDiagrams"`
	MermaidDiagrams        []*spec.MermaidDiagram       `json:"mermaidDiagrams"`
	SourceFile             string                       `json:"sourceFile"`
}

type ThreatModelFilter struct {
	Author         *string `json:"author,omitempty"`
	InternetFacing *bool   `json:"internetFacing,omitempty"`
	NewInitiative  *bool   `json:"newInitiative,omitempty"`
	InitiativeSize *string `json:"initiativeSize,omitempty"`
}

type TrustZone struct {
	Name string `json:"name"`
}
