// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"github.com/threatcl/spec"
)

type Attributes struct {
	NewInitiative  *bool   `json:"newInitiative,omitempty"`
	InternetFacing *bool   `json:"internetFacing,omitempty"`
	InitiativeSize *string `json:"initiativeSize,omitempty"`
}

type DataStore struct {
	Name             string  `json:"name"`
	TrustZone        *string `json:"trustZone,omitempty"`
	InformationAsset *string `json:"informationAsset,omitempty"`
}

type ExternalElement struct {
	Name      string  `json:"name"`
	TrustZone *string `json:"trustZone,omitempty"`
}

type Flow struct {
	Name string `json:"name"`
	From string `json:"from"`
	To   string `json:"to"`
}

type Process struct {
	Name      string  `json:"name"`
	TrustZone *string `json:"trustZone,omitempty"`
}

type Query struct {
}

type Statistics struct {
	TotalThreatModels      int      `json:"totalThreatModels"`
	TotalThreats           int      `json:"totalThreats"`
	TotalInformationAssets int      `json:"totalInformationAssets"`
	TotalControls          int      `json:"totalControls"`
	ImplementedControls    int      `json:"implementedControls"`
	AverageRiskReduction   *float64 `json:"averageRiskReduction,omitempty"`
}

type ThreatFilter struct {
	Impacts                []string `json:"impacts,omitempty"`
	Stride                 []string `json:"stride,omitempty"`
	HasImplementedControls *bool    `json:"hasImplementedControls,omitempty"`
}

type ThreatModel struct {
	Name                   string                       `json:"name"`
	Author                 string                       `json:"author"`
	Description            *string                      `json:"description,omitempty"`
	Link                   *string                      `json:"link,omitempty"`
	DiagramLink            *string                      `json:"diagramLink,omitempty"`
	CreatedAt              *int                         `json:"createdAt,omitempty"`
	UpdatedAt              *int                         `json:"updatedAt,omitempty"`
	Attributes             *Attributes                  `json:"attributes,omitempty"`
	AdditionalAttributes   []*spec.AdditionalAttribute  `json:"additionalAttributes,omitempty"`
	InformationAssets      []*spec.InformationAsset     `json:"informationAssets"`
	Threats                []*spec.Threat               `json:"threats"`
	UseCases               []*spec.UseCase              `json:"useCases"`
	Exclusions             []*spec.Exclusion            `json:"exclusions"`
	ThirdPartyDependencies []*spec.ThirdPartyDependency `json:"thirdPartyDependencies"`
	DataFlowDiagrams       []*spec.DataFlowDiagram      `json:"dataFlowDiagrams"`
	SourceFile             string                       `json:"sourceFile"`
}

type ThreatModelFilter struct {
	Author         *string `json:"author,omitempty"`
	InternetFacing *bool   `json:"internetFacing,omitempty"`
	NewInitiative  *bool   `json:"newInitiative,omitempty"`
	InitiativeSize *string `json:"initiativeSize,omitempty"`
}

type TrustZone struct {
	Name string `json:"name"`
}
